steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/csjp-gcloud/ministat'
  - '.'

- name: 'gcr.io/csjp-gcloud/ministat'
  id: Run build
  entrypoint: /build.sh
